### PR TITLE
uploading edited datasets and the line graph and scatter plot

### PR DESCRIPTION
**Pull request by ericyang91**
Uploading 2019 Jan ~ 2022 June Netflix's stock price and number of new daily cases worldwide for the corresponding dates.
Cleaned and merged the data.
Plotted line graph for each of the dataset.
Plotted scatter graph for further analyses.

Uploaded the Project Summary document with our hypothesis added.

### CODE REVIEW

**Comment by theidari** [comment]
The covid graph is not accurate, Could you check the data?

**Comment by ericyang91** [comment]
Oh can you please point out where?

**Comment by ericyang91** [comment]
I dropped the dates for new cases when the markets weren't open so we have corresponding dates.

**Comment by ericyang91** [comment]
I also calculated the correlation coefficient as well as the p-value. Let me know you guys before I push the remaining update! :)

**Pull request merged**
